### ISSUE TITLE
How should we acknowledge our contributors?

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#10]
At the moment the original leadership team - the people who contributed to the STEMM Role Models app idea in January 2016 - are listed in the [Meet the Team](https://github.com/KirstieJane/STEMMRoleModels/blob/master/MeetTheTeam.md) file, but we're hoping that more people will help out along the way.

What do you think is the best way to acknowledge their contributions?

**Comment by erich001** [comment]
[Here's](https://modelviewculture.com/pieces/acknowledging-non-coding-contributions) a page with a few thoughts. It ends up recommending [octohatrack](https://github.com/LABHR/octohatrack) to at least see all of your non-code contributors.

**Comment by KirstieJane** [comment]
I looooove this @erich001!

I downloaded [octohatrack](https://github.com/LABHR/octohatrack) and wrote up a [wiki page](https://github.com/KirstieJane/STEMMRoleModels/wiki/Using-Octohatrack) for how to use it. BUT then I reached out to the developers and they pointed me to [this interactive page](https://labhr.github.io/js-hatrack/#) that pulls up everyone who has contributed in real time.

The only problem with the page is that you have to be logged into GitHub to see the contributors so I made a [static version of our repo's page](http://kirstiejane.github.io/STEMMRoleModels/octohatrack_output/Scrapbook_20160317092940/index.html) on 17th March 2016.

I've also put some instructions [in the wiki](https://github.com/KirstieJane/STEMMRoleModels/wiki/Save-a-static-version-of-js-hatrack-page) on how to update this process.
