### ISSUE TITLE
Nav bar doesn't work on mobile

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#106]
So saaaad!

I can see the nav-bar but when I click on it it doesn't show me anything.

If anyone knows why please comment!

**Comment by Ryuno-Ki** [comment]
The JavaScript isn't loaded.

Open the developer tools of your web browser and look at the Network pane. For Firefox, it is explained [on MDN](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor).

**Comment by Ryuno-Ki** [comment]
I checked with Web IDE as well (you need to download an ISO and then hit the browser app on the left side to get access to Developer Tools there).
![screenshot_stemmrolemodels320x533px](https://cloud.githubusercontent.com/assets/3097194/19365939/637837a6-9195-11e6-99a6-0539a7aa4c92.png)

The image is too big. Related to #98?

**Comment by Ryuno-Ki** [comment]
Concerning [WebIDE](https://developer.mozilla.org/en-US/docs/Tools/WebIDE).

My battery runs dry in a few minutes.

**Comment by geminiimatt** [comment]
i am taking a look at this as well. more soon.

**Comment by amitkumarj441** [comment]
@KirstieJane Did you import the jQuery before importing bootstrap, out of order it won't work!
For ex:
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>`

**Comment by KirstieJane** [comment]
Hi @geminiimatt - thank you for taking this on - I'm going to assign you to this issue! [EDIT: wait - no I'm not because you aren't a contributor. Ok, you're virtually assigned :wink:] Very likely @amitkumarj441 and @Ryuno-Ki's comments will be helpful!

@Ryuno-Ki - the fact that the image is too big is a different issue!! It needs to be fixed too. If you have time and feel like it you could open a new issue to describe the problem!

Thank you all for your help :smile:

**Comment by amitkumarj441** [comment]
Hey @KirstieJane ,

I hope you checked my comment on this issue, well I'll soon fix this issue by adding the navbar switching part in js file. Let me assign this issue, I'm going to fix this bug.

Cheers,
Amit Kumar Jaiswal

**Comment by Ryuno-Ki** [comment]
Hey, @KirstieJane,

sadly I'm overloaded with work at the moment. But I'm still watching this repo and chime in, whenever I can help.

**Comment by stain88** [comment]
Hey @KirstieJane,

It looks like none of the pages source bootstrap js, and only the search_database page has jquery. I've added a cdn link to all the pages, and the dropdown now works, although the first couple of links sit next to the logo. Would it be worth having this as a navbar-brand class and moving it out of the collapse, so that it is always visible?

**E** I also did a bit of html-linting while in the files, there were a few instances of improperly closed tags, mis-matching tags

**Comment by Ryuno-Ki** [comment]
CDNs are fine. Until they got down (b/c of a DDoS, for example).

We should look after adding some decent styles in a `<noscript>` to keep the site usable.

**Comment by KirstieJane** [comment]
Thanks @stain88! I've merged your changes! And now the navbar works! Great!

BUT - I agree that it shouldn't have the logo on the inside of the collapse. Any pull requests on that front are very welcome :smile:

**Comment by stain88** [comment]
Cool, I'll work on that tomorrow

**Comment by KirstieJane** [comment]
@Ryuno-Ki I don't think DDoS happen often enough for a no script version to be of high priority. But if you or anyone else wanted to work on it then that's fine.

**Comment by stain88** [comment]
Problem is, I was silently laughing at that too, but then that whole DynDNS DDOS happened and took down Twitter, Github, Reddit, and others, so I'll put it in locally with the nav bar changes.
