### ISSUE TITLE
Multiple video links get merged

### ISSUE THREAD

**Issue by stain88** [KirstieJane/STEMMRoleModels#109]
Hey @KirstieJane,

It looks like multiple links in a role-model section (whether professional pages links, or videos) get merged into a single link.

It looks like this is due to the `words` variable in `app.js` being created via a regex split on "space",  but the links themselves are separated by new lines.

Changing the declaration to `var words = value.split(/ |[\r\n]+/);` seems to fix that, with no unwanted side effects.

**Comment by KirstieJane** [comment]
Closed! Thank you :smile:
