### ISSUE TITLE
Pages don't scroll on mobile

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#111]
Sigh! We fix the Navbar (see issue #106) but now the [Add](https://stain88.github.io/STEMMRoleModels/site/add.html) and [Write](https://stain88.github.io/STEMMRoleModels/site/write.html) pages don't scroll on mobile!

Anyone care to figure out why?!

**Comment by stain88** [comment]
I'm guessing you tested on an iPhone? It's all fine on a Nexus in Chrome and Firefox, but I was hoping it was just the iOS simulator that was being funny.

**Comment by KirstieJane** [comment]
Yes! I was using safari on an iPhone and they don't scroll properly 😭 

Good to know that the Nexus works!

**Comment by stain88** [comment]
Well, a quick hacky fix is to remove `overflow: hidden;` in the css, which shows the whole form, but overlaps the help panel.
(At least on Simulator)
