### ISSUE TITLE
how to create file with file name single /  

### ISSUE THREAD

**Issue by kaal-kali** [KirstieJane/STEMMRoleModels#118]
i think u didnt understand i am trying to explain u i got a task from my university i.e ucreate file with only name /
![Screenshot_2020-01-06_09-19-43](https://user-images.githubusercontent.com/58244222/71835157-e1580c80-30d6-11ea-9181-de643ce7ae1a.png)

**Comment by stain88** [comment]
Hey @kaal-kali,
`mkdir` is the command to make a directory. To create a file, the command would be `touch`.

However, `/` traditionally denotes the root level of the operating system, and creating a file with that name could lead to some confusion. Creating this file wouldn't really be recommended in practice.

As a side note, `cat` is used to read files only, not directories: hence the error messages for that command.

**Comment by kaal-kali** [comment]
dud 1st ill thanking u but how to make u couldnt tell me i need file with name [ / ] please help me only this day  available for me

**Comment by KirstieJane** [comment]
Thank you for replying @stain88. This question is not related to the project (which is currently on haiatus) so I'm going to close this issue.
