### ISSUE TITLE
Planning for Mozilla Global Sprint

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#19]
The [Mozilla Global Sprint](https://www.mozillascience.org/global-sprint-2016-site-and-project-applications-open) is 2nd and 3rd June 2016. Anyone can sign up to attend at https://ti.to/mozilla-science/gs2016-berkeley/en
- [x] Location - [Boalt Hall, Room 145, 215 Bancroft Way, Berkeley, CA 94704](http://maps.google.com/maps?q=37.8699%2C-122.253+%28Boalt+Hall%2C+Room+145%2C++215+Bancroft+Way%2C+%0ABerkeley%2C+CA+94704%29) 
- [x] Who will come?
  - We don't have all the information we need right now but maybe around 20-30 people??
  - At the moment we have 3 sprinters signed up :grinning:
- [x] Who will we invite to join us?
  - Seems like something that LOADS of groups across campus would be interested in... There may even be other MozSci sprints happening at that time.
  - So far sent to:
    - Georgeann at Helen Wills Neuroscience Institute (@KirstieJane)
    - BIDS admissions email (couldn't find a better one!) (@KirstieJane)
    - Berkeley Psychology admin (@KirstieJane)
    - D-lab front desk (@KirstieJane)
  - Please share the [link to sign up](https://ti.to/mozilla-science/gs2016-berkeley/en) widely!
- [x] AV equipment
  - Projector
- [x] Video streaming
  - Figure out how to get our remote participants to know what's going on!
  - https://public.etherpad-mozilla.org/p/sciencelab-2016globalsprint-webconferencing
- [x] Send in application
  - Done by @KirstieJane on 24th March 2016
- [x] Send in site hosting application
  - Done by @KirstieJane
- [x] Food and drink
  - Lunch is not provided but @KirstieJane will bring a bunch of Trader Joe's snacks :smile: 

What else should we consider?

**Comment by elizabethjm** [comment]
Kirstie, I can put out feelers about a meeting area at UC Berkeley. How many people and what would we need in the space? I'm sure we could use the Egyptology library in a pinch, it has nice big tables and fast Wifi, but no windows.

**Comment by KirstieJane** [comment]
Thanks @elizabethjm! I'm not at all sure about number of people. Maybe 20? Maybe more??

Egyptology library sounds great (sans the lack of daylight situation!). Can we talk and give presentations there too?

I had in mind reaching out to the folks at [D-Lab](http://dlab.berkeley.edu/) because I follow them [on twitter](https://twitter.com/dlabatberkeley) and I think running a sprint might be something they have expertise in. Seems like at the very least they'd be good to promote the sprint through :smiley:

If you fancied pinging them an email introducing us that would be killer, but it isn't hugely time-sensitive.

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
I just registered in Mozilla Sprint and will work remotely.
Got my virtual ticket. 
What all you say?

Thank you
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Great stuff @amitkumarj441! "See" you on 2nd and 3rd June :smiley: :sparkles:

**Comment by KirstieJane** [comment]
@elizabethjm and @erich001 have been helping me out find a place to meet on UC Berkeley campus from 9am to 5pm on the two days of the global sprint. I kinda love the idea of finding a meeting room in a library, possibly this one: http://www.lib.berkeley.edu/libraries/chemistry-library

If anyone has time to send an email that would be amazing...... I'll update here if I send one!

**Comment by KirstieJane** [comment]
AMAZING Sprint @elizabethjm @erich001 @colleenboodleman and @deniederhut! Thank you for coming along :grinning:
