### ISSUE TITLE
Adding STEMM Role Models project to MozSci Collaborate

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#2]
We need to figure out what files or details are required to have this project be listed on Mozilla Science Lab's [Collaborate](https://www.mozillascience.org/collaborate).

Based on @acabunoc's reply below we need to make sure we have the following:
- [x] project on GitHub
- [x] open LICENSE
- [x] readable README
- [x] Issues teased out in the issue tracker
  - [x] Have "good first bugs" <-- implemented in this project as "no code" or "question" labels
- [x] CONTRIBUTING.md: contributor guidelines
  - [x] with a way to get in touch with the team
  - [x] and a Code of Conduct
- [x] Roadmap: development status  
- [x] Mentorship: be ready to give quick feedback and engage with contributors

Can I ask for @neuroAmyo, @erich001 and @elizabethjm to have a look over these files and give me some feedback? Anything that you feel is missing or could be clearer would be great. Or just a simple thumbsup :thumbsup: would be killer :)

(GitHub emoji cheat sheet at: http://www.emoji-cheat-sheet.com)

**Comment by abbycabs** [comment]
Hey @KirstieJane!

This might help:
https://github.com/mozillascience/plan/issues/47#issuecomment-179852524

Let me know if you have any questions! I'll put this more public soon :smile:

**Comment by KirstieJane** [comment]
Can I ask for @neuroAmyo, @erich001 and @elizabethjm to have a look over these files and give me some feedback? Anything that you feel is missing or could be clearer would be great. Or just a simple thumbsup :thumbsup: would be killer :)

(GitHub emoji cheat sheet at: http://www.emoji-cheat-sheet.com)

**Comment by erich001** [comment]
So far so good!  :+1: Schematic for navigating the app coming soon!

**Comment by KirstieJane** [comment]
I'm going to call this done....it's time to let people give us feedback :anguished: :grin:

And to cross off a [milestone](https://github.com/KirstieJane/STEMMRoleModels/milestones/Join%20MozSci's%20Collaborate%20collection)! Woooo ;)
