### ISSUE TITLE
Create GitHub pages website

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#20]
Translate @erich001's kickass schematic (https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/SchematicDesign/conceptualdesign.pdf) into a workable website via the gh-pages branch of this repository.
- [x] Make github pages website
- [ ] Create holder places for each of the different pages mentioned in the schematic

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
I love this idea and I would like to design a github webpage for your repository.
I already forked STEMMRoleModels repo. Let me know your chosen **username** for your github webpage.

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - we already have a GitHub pages branch set up in the repository as the gh-pages branch.

We re-direct www.stemmrolemodels.com to the gh-pages [index](https://github.com/KirstieJane/STEMMRoleModels/blob/master/index.html) page.

If you wanted to work on some fun design stuff you could check out @neuroAmyo's home page suggestion (see issue #34) and see if you could implement a style sheet for it?? You don't have to but if it seems interesting then that would be great! :smiley:

**Comment by amitkumarj441** [comment]
Hi KirstieJane,
Thanks for letting me know about the GitHub page.
Please close resolved issues.

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - the issue is still open as the website isn't complete. There are two check boxes in the issue and only one has been completed. I hope this makes sense going forward!

**Comment by amitkumarj441** [comment]
Ohh! I was little confused that time!
Sorry for inconvenience!

**Comment by Ryuno-Ki** [comment]
PDF now lives at https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/conceptualdesign.pdf (master branch was deleted).

**Comment by KirstieJane** [comment]
Done done! `gh-pages` is our friend. CLOSED ISSUE! :grinning:
