### ISSUE TITLE
Update README.md with MozWOW information

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#3]
I'd like for visitors (potential new contributors) to know about the Mozilla Working Open Workshop so it would be great to include a short blurb (and maybe the Moz Science fox?) in the README file.

Anyone interested in having a go at this?

**Comment by RobSullivan** [comment]
Hi Kirstie, I'm interested in having a go. Will let you know when it's ready to review.

**Comment by RobSullivan** [comment]
Hi Kirstie, PR #4 is ready for reviewing.
