### ISSUE TITLE
Do you need analytics tracking to see how many users are going to your website? 

### ISSUE THREAD

**Issue by grprtkal** [KirstieJane/STEMMRoleModels#31]
Hi ladies, 

I am new to STEMMRoleModels. I found your project through a women in tech community group. I love this idea! I'm a front-end dev with experience in analytics tracking and a/b testing. 

If you need help getting a sense of how many users are coming to your site, please do let me know. I can add Google Analytics, MixPanel or another analytics tool so that you have greater sense of how users are interacting with your project. 

Great idea! 
Gurpreet

**Comment by KirstieJane** [comment]
Hi Gurpreet! Yaaaaaaay!!! It's 6:15am over here in the UK and I'm off to grab the train to work, but I wanted to say a huge hello and Yes!! Absolutely :smiley:

When you have some time, if you can comment below, or edit your original issue with some of the steps involved in adding analytics to the website - no need for every detail but particularly let us know if you need any information that isn't already in the repo - and then we can get started with your pull request! 

Thank you for getting in touch! I'm over the moon :sparkles: :tada: :sparkles:

**Comment by erich001** [comment]
Fantastic!! :+1:

**Comment by neuroAmyo** [comment]
This would be super helpful, indeed! Really exciting to have any help you can offer! :clap: :smiley:

**Comment by grprtkal** [comment]
Hi ladies,

I just forked the project! :) It looks like you already have a Google Analytics script up and running which is awesome (on index.html). I can add events like tracking the number of clicks on links you have on the site. I'd need some help verifying that the data is being tracking in GA (perhaps, you can double check the event is getting tracked in GA or give me temporary access to your GA, whichever you feel more comfortable with).

Cheers!
Gurpreet

**Comment by KirstieJane** [comment]
Heya! Thank you @grprtkal! I set up that google analytics and then totally wandered away from it because I had no idea what I was doing.

Fortunately I can add you so you can see what is going on. Can you ping me an email with the right address to add you as a user?

**Comment by KirstieJane** [comment]
Pull request #32 Merged! Thank you @grprtkal!

My email address for the google analytics/tag manager account is kirstie.whitaker.berkeley@gmail.com.

I'm going to leave this issue open for now (even though the pull request is closed and integrated) because it would be really great to document what we can do with the information from Google Tag Manager. I've made a [wiki page](https://github.com/KirstieJane/STEMMRoleModels/wiki/Using-Google-Tag-Manager) with the comments from your commit. If you have any time to add in some extra details that would be grand, otherwise I'll take a look when I have access.

Thanks again! It's so much fun to have new friends working on the project :smiley: :balloon: :tada:

**Comment by grprtkal** [comment]
Hi Kirstie,

I've added you as admin on Google Tag Manager. And thanks for starting a
wiki! I'll try to write up some things I know in a clear way :) My next
coming week is quite busy but I will try to add as much documentation as I
can. Also, since now you have merged the tag manager code, I can test to
make sure the data is still getting tracked in GA :)

I'm also having so much fun contributing to my first open source project,
especially for a topic that is very close to my heart (research and
technology!) :)

Cheers,
Gurpreet

**Comment by amitkumarj441** [comment]
Hi @KirstieJane,
I came across Mozilla Science Lab and recently I joined this project. You already created Google Tag Manager account and this is one of the best way to track visitors in one go. I'm good at Analytics especially GA and already managed GTM for one startup. So, I want to document GA and Google Tag Manager as you already started a wiki. Please let me know from where should i start documentation.

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - thank you for the offer to help document the Google Tag Manager tool. I've created a markdown document called [UsingGoogleTagManager.md](https://github.com/KirstieJane/STEMMRoleModels/blob/master/wiki_docs/UsingGoogleTagManager.md) in a new folder called [wiki_docs](https://github.com/KirstieJane/STEMMRoleModels/blob/master/wiki_docs). You can fork the repository (or update your own fork to be in sync with this master branch), add the documentation into that file and then submit a pull request.

As @grprtkal set up the Google Tag Manager tool I'm going to ask that she take a look at your documentation before I merge it as I know she was going to work on putting some notes together too. It might take a little while for her to get around to reviewing the pull request (see her comment above about a busy week) but I'm sure she'll appreciate the help getting the notes in order!

Thanks again to you both for helping push the project forwards :balloon: :balloon: :balloon:

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
Thanks for creating wiki_docs. 
I saw her comments and I will soon come up with a pull request.

Cheers,
Amit Kumar Jaiswal

**Comment by amitkumarj441** [comment]
Hi @KirstieJane!
Recently I submitted three pull request. Please have a look at these three.
Thank you for your time.

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - I'm not able to review pull requests every day. Every member of the leadership team has full time research positions and we're developing this project in our (very limited) spare time.

As I state in the [guide for contributors](https://github.com/KirstieJane/STEMMRoleModels/blob/master/CONTRIBUTING.md) I can pledge to reply to requests by Monday each week, when I have set aside time to work on this project. That means I can't guarantee to get to your pull requests before next Monday 11th April.

It may that we are not moving at a pace that is well matched with your goals at this time. If that is the case maybe it would be best if you diversified your contributions across projects?

**Comment by Ryuno-Ki** [comment]
I came across Mozilla Science Lab, too.
Speaking of Mozilla, [principle 4](https://www.mozilla.org/en-GB/about/manifesto/#principle-04) describes the value of privacy - I don't see that in Google Analytics or Google Tag Manager. Does it respect, for example [Do Not Track headers](https://en.wikipedia.org/wiki/Do_Not_Track)?

[Piwik](https://en.wikipedia.org/wiki/Piwik) would - but needs a server running.

@grprtkal Do you know any client-only Analytics software, which respects the user's privacy? I'm scared where Google knows that much about one's visitor (age, preferences, location …).

**Comment by grprtkal** [comment]
@Ryuno-Ki: Thanks for bringing up the privacy policy. This is a really good question. I'm honestly unsure whether Google Analytics or Google Tag Manager is in line with [principle 4](https://www.mozilla.org/en-GB/about/manifesto/#principle-04). 

I do feel like this may be a good question to bring up with the Mozilla advisors. What do you think @KirstieJane ?

**Comment by KirstieJane** [comment]
Thank you @Ryuno-Ki for bringing this up - I hadn't thought about it. @grprtkal - as you suggest - I'll ask @acabunoc when we chat this evening :smile:

**Comment by KirstieJane** [comment]
Hey @acabunoc - do you have any opinion about this discussion?

**Comment by abbycabs** [comment]
Hey! Sorry for the delay :) We use google analytics here at Mozilla, but we have a special agreement around how Google stores and uses the data that protects users' privacy (I don't know all the details)

**Comment by janhohner** [comment]
Hey all, if this is still recent here are my two cents on the matter: Because of privacy concerns with Google Analytics we're not allowed to use it on any of our university projects. We always use Piwik, which has mostly the same functionality, better settings on how exact IP-Adresses should be tracked, it follows the "do-not-track" setting in browsers and has a simple option for users to completely opt out of the tracking for the website. The downside to Piwik is that it's self hosted so I don't know if it's an option for you.

**Comment by KirstieJane** [comment]
Hey @grprtkal - I think after all this discussion we're best off taking google analytics off the site. Does that sound ok with you?

Thank you to everyone who has shared their expertise on this question! I really appreciate all the discussion :smiley:

**Comment by grprtkal** [comment]
Sounds good to me -- though after we test out the site with a couple people and have real people using we should have some sort of analytics platform in place. We can sort it out then. :)

**Comment by KirstieJane** [comment]
Hi everyone who's contributed to this thread! I'm on a clean up spree so I've taken out the google analytics tracking from the webpages right now (we can re-open this discussion in the future if necessary) and I'm going to close this issue!

There are a bunch of little html, css and js bits and bobs that I'd like to clean up with the database, so if you have any time to help out please do let me know! You can catch me on [gitter](https://gitter.im/KirstieJane/STEMMRoleModels), [twitter](https://twitter.com/kirstie_j) or send me an email :)

Thanks again for sharing all your expertise!
