### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by neuroAmyo** [KirstieJane/STEMMRoleModels#35]
I created a quick mockup of a logo (https://github.com/KirstieJane/STEMMRoleModels/blob/master/SchematicDesign/logoMockUp_160403.pdf). The logo is meant to highlight the fact that we're increasing visibility of women in science by fostering connections etc. It is admittedly somewhat generic, and I'm not sure if it properly captures everything we're about. But I thought it was worth sketching out a quick idea. 

Feedback much appreciated on:
- [ ] What ideas do we want to capture in our logo?
- [ ] Aesthetic goals for the logo?

**Comment by KirstieJane** [comment]
You I like the logo it's stylish and I definitely like the idea of building a network...but I also agree that it's quite generic.

When I was googling around for ideas I liked images like [this one](http://www.16hertz.com/wp-content/uploads/2015/02/Minorities-in-Stem.png) for the different skin tones etc. I think I was imagining a logo that had a bunch of different cartoon-y characters who all looked different representing diversity in STEMM.

But I have to admit, that the more I think about it, I'm not sure I like my idea. I think yours (@neuroAmyo) is much more sleek and stylish and I think that's the demographic we're going for - not fun and exciting for young girls but "take these women/people of color/people with disabilities seriously".

The other aspect that I'm really passionate about is making this not just about women. And I had thought that having different people would be good, but now I'm quite liking the idea of not showing "people" in the logo at all, but making it more about inclusivity in a more abstract sense.

Just some thoughts while I'm waiting for my train! Thank you for finding the time to put this together :smiley:

**Comment by erich001** [comment]
I like this one a lot!  In general I'd lean toward sleeker and more abstract. Chat with you guys soon! :smiley:

**Comment by neuroAmyo** [comment]
After chatting with one of my favorite people to get design feedback from (Helene M.!), here are a few ideas for directions to go from this basic idea worth throwing out there:
- incorporate science/tech more explicitly by making the "nodes" in the networks simple science icons. Examples: a beaker, an atom, a computer, a brain, etc.
- play with the network structure to try to capture the various relationships between the "newcomer" and the "established" network. 
  Some options include: making the existing nodes larger than the new (teal) one; restructuring network connections to change how the blue one connects with the rest of the network. A single contact? Or broader connections??

**Comment by neuroAmyo** [comment]
Had a bit of time this evening and took another crack at the logo. 

I tried the icons. I might play with it more, but it really looks a bit cartoony. I don't think the clipart-ish simple icons blend well with the more abstract network visuals. 

I did try modifying the network structure and cleaning things up a bit to make a new potential version: https://github.com/KirstieJane/STEMMRoleModels/blob/master/SchematicDesign/logo_v2.jpg
I added in differently sized nodes (to represent people at various stages in their careers). I also tried using color to convey the idea of role models (a few little nodes are being influenced by the newcomer). 

I'll probably play with this more (this is the sort of thing I could do for hours while watching tv at night before bed). Feedback welcome!

**Comment by KirstieJane** [comment]
I really like this @neuroAmyo - I think it's simpler and I think it better conveys the idea of bringing someone into an existing network. I get what you're doing with the colour but I think it's odd that the big node that's connected to the green node doesn't have any green in it. I guess that was on purpose because they're not necessarily in need of role models but I think it makes the spread a bit harder to see.

What do you think?

**Comment by neuroAmyo** [comment]
Yeah, I see your point. I'm still not completely sure on the color thing. (Partly because if you think about it too literally, it gets very confusing!) I changed the logo to a new version (https://github.com/KirstieJane/STEMMRoleModels/blob/master/SchematicDesign/logo_v2.jpg) where the teal is spreading across the network in a more visible/apparent way. 

I also added a 'banner' version that's very simple. This one has just 2 colors and a smaller network, and is arranged to be a bit more horizontal.

**Comment by KirstieJane** [comment]
Oooooh! These look great! Thank you @neuroAmyo :tada: :sparkles: :sparkling_heart: 
- I love the small network for the banner version. Super useful
- I think the fading of the colours works really well :smiley: 

Two picky bits of feedback (that I don't feel strongly about so feel free to say that you've thought about them but would rather not change thing!)
- I really like the fading of the colors - could we include those in the banner version? I think you've removed them for a reason but I wanted to put a little shout out for putting the fade back in.
- I'm not sure about having different fonts for the banner and main logos. I like the font in the main logo better. Does the banner end up being too long if we use that font?

And three requests:
- Please can you provide versions of the images as separate .jpg files?
- Please can you provide black and white versions of the images? (I think there are some situations in which it would be good to have a block black on white logo, not with shades of grey).
- Please can you provide a square version for our twitter logo?

**Comment by erich001** [comment]
:+1:  @neuroAmyo!
[This site](http://www.xiconeditor.com/) or something like it may be useful for generating smaller icons of the logo. A lot of line art doesn't scale down well to the size of icons/favicons, but this worked for me. :smile:

**Comment by neuroAmyo** [comment]
Thanks for the feedback @KirstieJane :smiley: 
A few thoughts:
The text on the banner is the same. Just not bold. I had thought it would look better/simpler. But in playing around with it, I think the bold is fine. 
Removing the color gradients on the banner logo was to simplify. I figured a small logo should really only have ~2 colors and very few details. But in playing around, I honestly think both look fine. I think if it's _very_ small, we might want the stripped down version. But for something like a banner, it's probably ok to include. 

And great idea for the square logo! 

I had a bit of fun playing with the logo and making various options. Might've gotten a bit carried away. But I created jpeg images with a few options of the "full logo" (https://github.com/KirstieJane/STEMMRoleModels/blob/master/SchematicDesign/logo_full_options.jpg), banner logo (https://github.com/KirstieJane/STEMMRoleModels/blob/master/SchematicDesign/logo_banner_options.jpg) and a square logo (https://github.com/KirstieJane/STEMMRoleModels/blob/master/SchematicDesign/logo_square_options.jpg). 

I played the most with the square logo since it was quick to generate lots of different kinds. (And I suspect this sort of logo will be useful for things like twitter, as you mention @KirstieJane ). If we like any of these color combos, they can easily be extended to banner and full logo versions, too. 

Votes for favorite(s)? :)

**Comment by Ryuno-Ki** [comment]
master branch is no more. Hence the resources are now available at:
- https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logoMockUp_160403.pdf
- [![logo v2](https://github.com/KirstieJane/STEMMRoleModels/raw/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_v2.jpg)](https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_v2.jpg)
- [![logo square options](https://github.com/KirstieJane/STEMMRoleModels/raw/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_square_options.jpg)](https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_square_options.jpg)
- [![logo banner options](https://github.com/KirstieJane/STEMMRoleModels/raw/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_banner_options.jpg)](https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_banner_options.jpg)
- [![logo full options](https://github.com/KirstieJane/STEMMRoleModels/raw/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_full_options.jpg)](https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/logo_full_options.jpg)

**Comment by Ryuno-Ki** [comment]
Concerning the images: Keep in mind that JPEG does not support alpha channels, that is, no transparency.

For simple graphics, PNG or even SVG may be preferable (SVG scales well as it is a vector image format). There are tools to convert one into another (like GIMP, Inkscape or ImageMagick), but most the time, you will "loose information", which yields "artifacts" like rough edges or similar. JPEG is meant as photographic format (for example, for selfies).

**Comment by KirstieJane** [comment]
Hey @neuroAmyo! I'm going to close this issue because I love the logos you've made! Thanks to everyone who provided feedback :grinning:
