### ISSUE TITLE
Amit Kumar Jaiswal: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by amitkumarj441** [KirstieJane/STEMMRoleModels#36]
I am a IIIrd year undergraduate of Computer Science currently pursuing my Bachelor in B.Tech and I'm an active open source contributor and Mozillian and having done academic projects in Database where my work involved as a Frontend and Backend developer, that's why this project amuse me to form my interest in particular. If I have given a chance then I will be proven asset to your organization.<p><br><blockquote>This issue was created by @amitkumarj441 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by KirstieJane** [comment]
Hi @amitjumarj441! Welcome to the project. Have a look through our issues and the readme and see if there are any you fancy working on. Or if you see a place that you can contribute please go ahead and make a new issue and suggest it! 

Thank you for joining the team - we're excited to have you! :balloon::balloon::balloon:

**Comment by amitkumarj441** [comment]
Thanks for your prompt response. 
I'll soon commit a new issue or a pull request.

**Comment by KirstieJane** [comment]
Hey @amitkumarj441 - I'm going to close this issue because you're totally a team member now and I'm on a clean up spree :grinning:
