### ISSUE TITLE
Transforming our draft pages into HTML and CSS

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#48]
@neuroAmyo has created two great diagrams sketching out what we'd like our website to look like (for details see issue #34).
- [Home page](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/SchematicDesign/homePageMockUp.pdf)
- [Profile page](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/SchematicDesign/profileLayoutMockUp.pdf)

**_Does anyone fancy trying to re-create these as HTML and CSS files?**_

I (@KirstieJane) am very happy to help out. I'm currently taking a responsive web design Coursera course and so I've got some understanding of HTML, CSS and bootstrap. I'm asking for help though because I'm mega busy at the moment....and you are very likely much more expert than me!

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
Great job! Awesome! 
This seems me quite exciting and I would like to re-create all these stuffs as HTML & CSS files.
Please let me know where to initiate the pull requests for these files.

Cheers,
Amit Kumar Jaiswal

**Comment by grprtkal** [comment]
Hi @KirstieJane and @amitkumarj441, 

I have some time this week. I can help take a look at the pull request at @amitkumarj441's HTML & CSS once it's done. I suggest we start with using Bootstrap as a framework to keep things simple. 

Perhaps later on, once we start using dynamic data regarding user profiles we can start using Angular. 

Gurpreet

**Comment by KirstieJane** [comment]
Hi @grprtkal. I'd love for us to use Bootstrap because I'm taking a course in it and it would make it much easier to implement.

Thanks again for offering to help (so sorry I'm so slow getting back to you!)

I think @amitkumarj441 is doing exams for the next couple of weeks so if you still have time and fancy making a new look for the website that would be great!

**Comment by amitkumarj441** [comment]
Hi @KirstieJane , I already built a static website using Bootstrap & HTML as a part of academic project and know how to play with web stuffs. As @grprtkal suggested us to use Bootstrap as a framework, i can make a static website using Bootstarp &HTML in new look.

**Comment by KirstieJane** [comment]
Thanks @amitkumarj441. I don't want to close off opportunities for others to contribute to the project while you have exams. But definitely do check back in when you have time to work on the implementation to see if anyone else has made any progress.

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
Sure! I'll be onto this only. As soon as i get free I'll soon come up with a new pull request over this topic.

Cheers,
Amit Kumar Jaiswal

**Comment by grprtkal** [comment]
Hi @KirstieJane, 

I'm playing around with Yeoman and am trying to use a mockup of either the homepage or profile page. I think the URLs to the pdfs are no longer working.  I know I've seen them somewhere before :) Do you mind publishing it again? Thank you! :)

I have some time over the next two weeks to contribute. @amitkumarj441 I can get started and then share with you what I have. 

Thanks,
Gurpreet

**Comment by amitkumarj441** [comment]
Hi @grprtkal ,

I also encountered the same problem while accessing those URLs to the pdfs, it took a longer time to load. Then I find a way to access these pdfs, go to code -> Schematic , then try to open those pdfs from there. It's working fine when i go through the above steps. 
Hope you'll able to see these pdfs.
Sure! I would like to code and document as well.

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Thanks @grprtkal for pointing out the broken links. They were pointing to the now extinct master branch! I've fixed them now :smiley:

**Comment by grprtkal** [comment]
Hey ya'll, 

I created a pull request for the homepage #56. @KirstieJane, please take your time. It's a lot of new code/files! (I have some time off and can commit some extra time for the next week or so!) :) And definitely let me know if there's anything I can do on my end to clear up any parts. 

@amitkumarj441 The responsive design needs some help :) If you're up for it, perhaps you can help with that?

Thanks,
Gurpreet

**Comment by KirstieJane** [comment]
Thank you @grprtkal for your great work setting up the home page and CSS :)
