### ISSUE TITLE
Image link broken on homepage (404)

### ISSUE THREAD

**Issue by eddiejaoude** [KirstieJane/STEMMRoleModels#51]
Clicking on...
<img width="1109" alt="screenshot 2016-04-22 07 33 48" src="https://cloud.githubusercontent.com/assets/624760/14733673/abe8e12e-085c-11e6-9d7c-87a97994ace1.png">

Gives...
<img width="900" alt="screenshot 2016-04-22 07 33 57" src="https://cloud.githubusercontent.com/assets/624760/14733680/b794cc7c-085c-11e6-9449-62fa4b4ce41d.png">

**Comment by KirstieJane** [comment]
Amazing @eddiejaoude! Thanks for pointing out the broken links!! Will hopefully merge the PR tomorrow :smiley:
