### ISSUE TITLE
lpix: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by lpix** [KirstieJane/STEMMRoleModels#60]
Hi!
What an interesting project! Right now I am on my way to getting a certificate for Front End Developing so I hope  to be putting my coding skills to good use here.
Looking forward to working with you!
Leslie<p><br><blockquote>This issue was created by @lpix via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by KirstieJane** [comment]
Hi @lpix! Thank you for getting in touch. We'd love to have you join the team.

I know that part of the work I need to do (soon) is tidy up some of the issues and the [roadmap](https://github.com/KirstieJane/STEMMRoleModels/issues/1). As you're exploring the repository please feel free to comment on anything that's broken or doesn't make sense anymore!

We have a [gitter chatroom](https://gitter.im/KirstieJane/STEMMRoleModels) if you'd like to chat (it isn't used much but I'd love for that to change!) and stay tuned for more updates around our plans for the [Mozilla Global Sprint](https://www.mozillascience.org/global-sprint-2016) on 2nd/3rd June.

**Comment by KirstieJane** [comment]
Hey @lpix - I'm going to close this issue because I'm on a clean up spree. But please do keep following along the project and let us know if there's anything you'd like to work with us on :grinning:
