### ISSUE TITLE
Colleen Boodleman: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by cols2M08** [KirstieJane/STEMMRoleModels#64]
<p><br><blockquote>This issue was created by @colleenboodleman via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by KirstieJane** [comment]
Thanks so much for coming along to MozSprint @colleenboodleman :grinning: 

I'm going to close this issue because I'm on a clean up spree!
