### ISSUE TITLE
Create form for speakers who are recommending themselves

### ISSUE THREAD

**Issue by deniederhut** [KirstieJane/STEMMRoleModels#67]
The current workflow is a two part process, with recommender submitting information about a speaker here - http://goo.gl/forms/Hq0MpE4tC6VO8CmX2 - and then the speaker getting an email to submit information about themselves here -  http://goo.gl/forms/M1cst9YZoP0z8kW53. There is currently no way for a speaker to submit themselves without going through this two part process.

**Comment by KirstieJane** [comment]
I've changed the wording a little on the recommendation form to say that it's ok to recommend yourself! I think that's fine for now - I'm happy to close this issue for now and re-visit it if there's too much confusion!
