### ISSUE TITLE
On what platform should we develop the app?

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#7]
There are loads of ways to build websites, web apps and mobile apps. So which path should we choose?!

I've been working on a [responsive web design](https://www.coursera.org/learn/responsive-web-design/home/welcome) coursera course that recommends [Meteor](https://www.meteor.com/) as a platform. The benefits are that you build a website with meteor and then it creates the mobile apps for you so you don't have to do any work with the different native mobile platforms.

Another suggestion is [Foundation](http://foundation.zurb.com/) which is apparently nice and easy to use to create web apps.

A sensible plan may be to focus first on building a website rather than an app, and then transition to an app after that's developed.

What do you think?

**Comment by grprtkal** [comment]
Hi Kirstie, 

I agree there are so many different ways to get an app up and running (and so many frameworks!). Yeoman is a cool scaffolding tool (http://yeoman.io/) which is helpful in getting a new project up. It basically provides all the boiler plate code (directories, infrastructure, etc) so you don't have to spend time figuring out how to organize your app and does it in a way that uses best practices. It's JavaScript based and uses Angular JS.  

Perhaps give Yeoman a try? If it still takes too long to get an app up and running then ditch it and make a simple site? I'd personally love to give Yeoman a try. 

Also, I've used Bootstrap before for CSS but I've heard Foundation is better for responsive design.

Cheers, 
Gurpreet

**Comment by KirstieJane** [comment]
Sounds fantastic! I'm totally up for giving whatever tools our developers (you @grprtkal) are interested in. 

The main criterion is that it's reasonably "easy" and commonly used, that way we can benefit from as broad a contributor base as possible.

Thanks for the information, and feel free to keep running with Yeoman if you have the time and inclination :smiley:

**Comment by amitkumarj441** [comment]
Hi @grprtkal, 
I'm interested and this seems me a nice idea. Yeoman is obviously a great tool. I'm good at JavaScript. @KirstieJane Please let us know where to start this.

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Thanks @amitkumarj441 for the :+1: to Yeoman!

I'm not an expert in front-end development so at the moment I'm happy to solicit suggestions and proposals. If you want to play around with Yeoman and put together a demo page that sounds like a great plan! Another possible way forward is to build a bit of documentation around why Yeoman is so good. I've made a [Why_Yeoman.md](https://github.com/KirstieJane/STEMMRoleModels/blob/master/wiki_docs/Why_Yeoman.md) file in the [wiki_docs](https://github.com/KirstieJane/STEMMRoleModels/blob/master/wiki_docs) directory if you want to start outlining your plans :smiley: 

I'm going to keep this issue open for a little longer to see if we get any other strong suggestions. But thank you again to both @amitkumarj441 and @grprtkal for your expertise!

**Comment by jvoytek** [comment]
I'd second the idea of an "opinionated framework" like Yeoman. Since there will be many hands working on this project having some baked in rules to live by will make coordination much easier. I'm also a fan of coding standards, "linting" and unit/integration testing for projects with many contributors to help ensure code quality and reduce bugs. I'll start a new issue for these.

**Comment by jvoytek** [comment]
The last time I really looked at Meteor it was still too young to be stable. I think that has changed but it's still a little too "opinionated" for my taste (I realize in my last comment I made an argument for opinionated frameworks, but I think there's a goldilocks zone here). A MEAN (MongoDB, Express, AngularJS, and Node) stack is definitely my preferred stack at this point, and there's even a really handy Yeoman generator (https://github.com/angular-fullstack/generator-angular-fullstack) for getting everything setup.

**Comment by amitkumarj441** [comment]
Hi @jvoytek,
I already stated the idea of "opinionated framework" **Yeoman** in Why_Yeoman in new pull request.
Better if we start developing app using **Yeoman** from scratch i.e. from Idea -> Planning -> Analysis -> Coding & Testing -> Deploy. What all you say? @KirstieJane @grprtkal

**Comment by KirstieJane** [comment]
Thank you @jvoytek for your thoughts! I like the idea of the Goldilocks solution!!

**Comment by KirstieJane** [comment]
@amitkumarj441 - when you say "better ... developing ... from scratch" what do you mean? Better than what? What's the alternative?

**Comment by amitkumarj441** [comment]
Hi @KirstieJane, I said, it would be better if we start developing web apps using Yeoman rather than using Meteor or Foundation. Alternatives are Meteor & Foundation.

**Comment by KirstieJane** [comment]
So - I feel like we're converging on [Yeoman](http://yeoman.io/). What are the next steps in getting up and running?

**Comment by jvoytek** [comment]
I started playing with setting up an example website withYeoman using the angular-fullstack generator this weekend. I will commit the results soon for others to peruse along with my impressions of it for project setup and ongoing development.

**Comment by jvoytek** [comment]
Just posting my pull request for the Yeoman angular-fullstack demo site here: https://github.com/KirstieJane/STEMMRoleModels/pull/53

Not that we should actually merge it but at least this way it's in the system.

**Comment by KirstieJane** [comment]
Thank you so much to everyone who joined in this discussion!

At this stage I think we're best off focusing on developing a responsive website (using bootstrap) rather than an app, mostly because I'm a huge bottleneck in terms of reviewing the code! Once we have a minimum viable product in a simple way then we can come back to this discussion of frameworks :grinning:

Thanks again!
