### ISSUE TITLE
Formatting the FAQ page

### ISSUE THREAD

**Issue by erich001** [KirstieJane/STEMMRoleModels#72]
We are currently populating the [FAQ page](http://stemmrolemodels.com/site/faq.html) with text (still a work in progress), but could use some help with formatting. 

We would like the outline questions at the top of the page to be clickable links to the answer lower down.

For example, if you click on the question "What is a testimonial?" in the top list, it will re-frame the page so that the answer to the question "What is a testimonial?" is centered in the screen.

The file to edit is [here](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/site/faq.html).

Any help would be greatly appreciated!

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,
Count me in. I'm ready to help with formatting!
Please do let me know where to start.

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - can you see if you can answer @erich001's request above and turn the questions at the top of the [faq page](http://stemmrolemodels.com/site/faq.html) into links to the answers that come below?

**Comment by amitkumarj441** [comment]
Yes @KirstieJane , sure! I'll do that and I'm gonna initiating a PR for the same!

**Comment by KirstieJane** [comment]
I'm done it - woooo!
