### ISSUE TITLE
Gradient fade appearing in the middle of speaker view overlay

### ISSUE THREAD

**Issue by deniederhut** [KirstieJane/STEMMRoleModels#78]
The problem seems to stem from one or both of:
- [line 513](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/stylesheets/style.less#L513)
- [line 597](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/stylesheets/style.less#L597)

in style.less. Not sure if this is worth fixing now if the overall idea is to replace all of the CSS with bootstrap later.

**Comment by KirstieJane** [comment]
Heya - I think this would be pretty nice to fix, but not a super high priority. If anyone is browsing through issues and want to figure it out please comment and feel free to give it a bash :)

**Comment by KirstieJane** [comment]
Pretty sure this is fixed now but just commenting out a few lines....I've left them in just in case but I haven't noticed anything not working as a result.

CLOSED! WOO 🎉

**Comment by deniederhut** [comment]
Yay!
