### ISSUE TITLE
Writing the Contribute page

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#80]
We have a great [guide for contributors](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CONTRIBUTING.md) but we need to transfer some of those details (probably not all) to the [contribute](http://stemmrolemodels.com/site/contribute.html) page

One thing to note is that I'm not 100% sure that we want to call this a "Contribute" page. I think it might be mistaken as a page to add to the database! Maybe calling the page "Develop"??

Note that this issue is not the place to comment on formatting of the page. Go ahead and make a new issue for that if needed :smile:

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,

This is really awesome. Great work :+1: :100: . I would like to work on [contribute](http://stemmrolemodels.com/site/contribute.html) page. Please let me know where to start first.

Thank you
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - the best place to start is our guide for contributors - take a look there and think about which pieces of information should be transferred to the website for people who come along and want to learn more about developing the project :smile: 

I won't be able to give feedback until July 1st, but feel free to give it a bash if you'd like!

**Comment by ghost** [comment]
Can we explain how to contribute by using some graphical stuff or diagrams I think it will be more attractive rather than writing traditional doc.I know doc will be needed but we can try some other way that we can create interest for technical as well as non technical contributor for this.

**Comment by raj-maurya** [comment]
@drashti4 great thought :+1: , 

We need to design a title icon for the STEMMRoleModels.  I think this would be a good start. What do you think?

Thanks!

**Comment by ghost** [comment]
@raj-maurya cool.But have doubt is title icon is equal to logo of STEMM or something else?

**Comment by KirstieJane** [comment]
Hi @drashti4! Thank you for your suggestion! I like it - I think diagrams are way more friendly than text!

Do you want to put a sketch together to show what you're thinking of?

@raj-maurya - I think your suggestion of needing a smaller logo so we can use it as a title icon is great but not related to the documentation issue (unless I'm misunderstanding @drashti4's point).

(FYI the logos are in the [SchematicDesign](https://github.com/KirstieJane/STEMMRoleModels/tree/gh-pages/SchematicDesign) folder. But again, I don't think that's relevant for this issue.)

**Comment by ghost** [comment]
@KirstieJane Yes you got my point. @raj-maurya join https://gitter.im/KirstieJane/STEMMRoleModels this room If you already there just send message in it about this idea.We can create some graphical tree or sort of classified pictures where It will show contribution area(Labels).

**Comment by raj-maurya** [comment]
Thanks @drashti4

**Comment by ghost** [comment]
![photo_2016-09-08_16-43-27](https://cloud.githubusercontent.com/assets/9081004/18347496/7ae95e60-75e3-11e6-9e8a-fe214ded42e3.jpg)
![photo_2016-09-08_16-43-30](https://cloud.githubusercontent.com/assets/9081004/18347497/7c8be8a0-75e3-11e6-9d10-d6560b2615cf.jpg)
![photo_2016-09-08_16-43-23](https://cloud.githubusercontent.com/assets/9081004/18347499/7e8ff4e8-75e3-11e6-9de2-7ca2ce8f273c.jpg)

I have made this design for contribution page.Main reason is contributor should not have to open multiple tabs for opening each link and menu will also be less and concise so he/she can easily remember in which menu contributor was. It will be simillar to Rust documentation(https://doc.rust-lang.org/stable/book/getting-started.html) but we can create tree structure for main menu page like in thoughts or issue menu.

**Comment by KirstieJane** [comment]
Hi @drashti4 - thank you so much for putting these suggestions together.

I think this is aiming too high for the website as it stands at the moment. I'm very happy for you to continue to work on your plans if you feel strongly about them, but I think there are many other areas to focus on before we need to implement a contributing page that is this detailed.

**Comment by ghost** [comment]
I just start contributing by seeing help wanted label.I am unaware of those areas.Can you tell me what are they?

**Comment by KirstieJane** [comment]
I'm going to close this issue as I don't think we need to have a separate contributing page on the website, we just need to make sure anyone who wants to join the developer team can find the [CONTRIBUTING.md](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CONTRIBUTING.md) file in the repo.

Thanks everyone for all the great discussions.
