### ISSUE TITLE
Create mailchimp mailing lists

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#81]
It would be great to be able to stay in touch with people who want to know more about the project, and to do so we're going to use www.mailchimp.com and send out regular newsletters.
- [Project updates](http://eepurl.com/bY8gtz) mailing list
- [Development updates](http://eepurl.com/b4sPmr) mailing list

**Comment by KirstieJane** [comment]
Hey @neuroAmyo - if you had any time to work your magic formatting these forms to make them beautiful I'd love to see them looking better :)

**Comment by amitkumarj441** [comment]
Hi @KirstieJane ,

I'm already on the list and just signed up on mailchimp.
I'm awaiting for some cool development tasks. Please let me know about some new task, I'm still awaiting.

Thank you
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - I've been on holiday for the last few weeks. I'm going to be away for the rest of June but then very happy to get back working on the project in July. Stay tuned!

**Comment by amitkumarj441** [comment]
Happy Holiday @KirstieJane ! :100: Enjoy the day and this June too!

**Comment by neuroAmyo** [comment]
Hi @KirstieJane. I made a STEMM Role Models template on mailchip a while back. Is there something different you want in terms of formatting for the two different update lists?

**Comment by KirstieJane** [comment]
Thank you @neuroAmyo!! The lists look great!

Here are the links - I'll integrate them into the website later today :smile:
- [General project updates](http://eepurl.com/bY8gtz)
- [Development updates](http://eepurl.com/b4sPmr)

**Comment by KirstieJane** [comment]
Right - I've added these links (in a super ugly way!) to the [contact page](http://stemmrolemodels.com/site/contact.html).

More formatting needed there FOR SURE, but I'm going to close this issue because the mailing lists are done :grinning:

Thanks for all the help @neuroAmyo!!

**Comment by amitkumarj441** [comment]
#87
