### ISSUE TITLE
Replace Login and Join with Search Database in the nav bar

### ISSUE THREAD

**Issue by amitkumarj441** [KirstieJane/STEMMRoleModels#83]
I just gone through [Login](http://stemmrolemodels.com/site/login.html) page & [Join](http://stemmrolemodels.com/site/join.html) page and here i found that there is no login and join portal.

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - that's because the way we have the database set up right now (through google docs) we don't need people to login or join. They'll provide their information via the google form they fill in.

**Comment by amitkumarj441** [comment]
Hi @KirstieJane , 

It's okay! It has been a long time since I met you last on Gitter.
Can I discuss with you on Gitter right now or can PM you on Twitter related to [UI of STEMMRoleModels](http://www.stemmrolemodels.com/)?

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - I only have 10 mins before I have to leave to catch a flight - but I'll join the [gitter room](https://gitter.im/KirstieJane/STEMMRoleModels) now :)

**Comment by amitkumarj441** [comment]
Hey @KirstieJane!

It has been a long time since I met you last, now back to work and would like to hit the ground of [STEMMRoleModels](http://www.stemmrolemodels.com/) running!
Let me assign this task first and then I'll take one on another to achieve the goal of this project!
What did you think?

Cheers,
Amit Kumar Jaiswal

**Comment by KirstieJane** [comment]
I think what needs to happen here is that we replace `Join` and `Login` with a `Search Database` link that goes to the [search database](http://stemmrolemodels.com/site/search_database) page.

Nothing fancy, but I think that top right corner would be a good spot :smiley: 

@neuroAmyo - does this make sense to you? The way in which the project has evolved means we don't really need the login and join buttons.....

**Comment by amitkumarj441** [comment]
Alright @KirstieJane ! I like this idea.

**Comment by KirstieJane** [comment]
Hi @amitkumarj441 - I've re arranged the nav bar so we're all set on this issue for now. Thanks for your help!
