### ISSUE TITLE
New Volunteer via Mozilla Science Lab.

### ISSUE THREAD

**Issue by raj-maurya** [KirstieJane/STEMMRoleModels#84]
Hello:

My name is Raj Kumar Maurya, currently a senior undergraduate student of Computer Science and Engineering. I have some experience in Frontend and Backend development and have done open source contributions, and I am a Mozillian, FSA as well. I have done some academic projects mainly focused on database design and development and also interned at few Tech. startups and Research organisations in past [LinkedIn](https://in.linkedin.com/in/raj-maurya-779b495b) and [Web](http://raj-maurya.github.io/). If given a chance to contribute to this project, It would be a good fit as per my interest and domain.

Thank You!
Raj Kumar Maurya

**Comment by KirstieJane** [comment]
Hi @raj-maurya!! I'm so sorry for the slow reply to your message! I've been on holiday and distracted with lots of other work but I'm really looking forward to getting back on track with the development of the project.

Thank you for joining the STEMM Role Models team! Are there any particular issues that you like the look of?

**Comment by KirstieJane** [comment]
Hey @raj-maurya! You're officially in the team now so I'm going to close this issue (I'm on a bit of a clean up spree!) Welcome! :sparkles:
