### ISSUE TITLE
Writing documentation for google forms/sheets database

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#85]
I'm writing up some documentation for how the google database currently works [here](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/documentation/how_the_database_works.md).

I have a couple of questions though for @deniederhut. It looks to me like the first two lines of the [config.js](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/js/config.js#L2) file link to a google sheet that Dillon, Erin and I (the Berkeley Global Sprint dream team) have access to, but is otherwise private.

That file has three sheets at the moment called `Data`, `Initial Recommendation` and `Speaker Survey`. 

Do those two lines in the javascript file make _just_ the `Data` sheet publicly available? Is it ok to keep private information in the other sheets?

**Comment by KirstieJane** [comment]
Hey @deniederhut! This is a question for you if you have any time to take a look :grinning: 

Thank you! :balloon:

**Comment by deniederhut** [comment]
Hey @KirstieJane ! Sorry for not responding sooner -- I've been in the middle of moving. To answer your question, it only provides an API call to the `data` sheet. It does not specifically restrict access to the other spreadsheets -- this is what our share settings do.

However, this raises another problem (I can make this a new issue). The google sheets are currently hosted in Berkeley's Drive app, which will disappear _probably_ in May of 2017. They should be migrated, and the code updated, sooner rather than later.

**Comment by KirstieJane** [comment]
Wooo - hope the move is going well @deniederhut! 

So - just to check I'm super clear - it's a setting on the google sheet that makes the API able to access the only the data sheet, not anything in the config.js code, is that right? I'm having trouble finding where to set the sheet level sharing settings on the google sheets page so maybe I'm still not understanding properly.....

Thanks for all the help!

**Comment by deniederhut** [comment]
Correct - access is controlled on the Google side. This was a while ago now, but I think the relevant setting is inside the spreadsheet itself, and it should be called something like **publish**. This allows you to give public access to individual sheets within a file, without making the whole spreadsheet publicly accessible.

**Comment by KirstieJane** [comment]
YES! That's exactly right!! GAH - thank you! I feel like I've looked in every drop down menu except that one :smiley: 

Brilliant - thank you @deniederhut :cake: :beers:

**Comment by KirstieJane** [comment]
I'm calling this good enough for jazz :saxophone: - DONE
