### ISSUE TITLE
Migrate data to new Drive ownership

### ISSUE THREAD

**Issue by deniederhut** [KirstieJane/STEMMRoleModels#92]
The current location of the web app data (e.g. [the data sheet](https://docs.google.com/spreadsheets/d/147nwbdx3D4kGywszzghfODm8SoOisASisjr9sU39Dr8/edit#gid=0) are in drive.google.com/a/berkeley. @deniederhut's institutional access to this location ends soon, which means the data will become inaccessible.

The spreadsheets and forms should be moved to another user's account -- preferably a user who also has admin access to this project -- before the end of this calendar year. IIRC, the only code that needs to be updated to reflect the change after the data move is the header of the [config.js file](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/js/config.js) with the new spreadsheet ID.

**Comment by KirstieJane** [comment]
Great stuff! Thank you @deniederhut - I've assigned myself to this - I'll make a copy of the file and update the config.js file!

**Comment by KirstieJane** [comment]
Done!! Yaaay 🎉 🎈

**Comment by deniederhut** [comment]
Woo!
