### ISSUE TITLE
Format the search page to look like the rest of the site

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#95]
At the moment our lovely search page has very different formatting to the rest of the site. It would be great to be able to have it fit rather more seamlessly with the other pages!

Search page: https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/site/search_database.html

FAQ page (as an example): https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/site/faq.html

**Comment by abbycabs** [comment]
To view the pages:
Search page: http://stemmrolemodels.com/site/search_database
FAQ page: http://stemmrolemodels.com/site/faq.html

Your search page is loading in its own stylesheets:
https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/site/search_database.html#L3
https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/site/search_database.html#L4

You should probably style it with the same stylesheet as your FAQ page:
https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/site/faq.html#L16

**Comment by KirstieJane** [comment]
Thanks @acabunoc!

I'm on my phone and will be offline this evening so I'll update this issue with more details tomorrow morning.

But in words - the other thing I'm not sure about is moving the buttons that are (I think) currently in the navbar on the search page to somewhere else on the page (because I'd like the standard nav bar to keep the theme all the same).

If that doesn't make sense then stay tuned and I'll integrate your suggestions and get back to you!!

Thank you!

**Comment by abbycabs** [comment]
Moving the button should be fine! 

Just move this line elsewhere:
https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/site/search_database.html#L37

**Comment by KirstieJane** [comment]
Ok - success has already started - with the major breakthrough running a local server so I can play around with the code! I was doing it all though committing to github before and that was CRAZY 🍌 🍌 🍌 

Now to figure out which parts of the style sheet need to be changed. Thanks for the help @acabunoc!

**Comment by KirstieJane** [comment]
YEEEEEEES. DONE. I want to cry I'm so happy! 😄  Thank you!

http://stemmrolemodels.com/site/search_database.html

**Comment by auremoser** [comment]
:) Thank you @acabunoc , I'm sorry i didn't get to this @KirstieJane !
